language: android

sudo: false

install: true

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

cache:
  directories:
    - $HOME/.m2
